// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using abbeys_bakery_api.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace abbeys_bakery_api.Entities
{
    public partial class AbbeysBakeryContext
    {
        private IAbbeysBakeryContextProcedures _procedures;

        public virtual IAbbeysBakeryContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AbbeysBakeryContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAbbeysBakeryContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetOrderDetailsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class AbbeysBakeryContextProcedures : IAbbeysBakeryContextProcedures
    {
        private readonly AbbeysBakeryContext _context;

        public AbbeysBakeryContextProcedures(AbbeysBakeryContext context)
        {
            _context = context;
        }

        public virtual async Task<int> CreateOrderAsync(Guid? UniquUserId, Guid? UserTableId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UniquUserId",
                    Value = UniquUserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "UserTableId",
                    Value = UserTableId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[CreateOrder] @UniquUserId = @UniquUserId, @UserTableId = @UserTableId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GetOrderDetailsResult>> GetOrderDetailsAsync(Guid? UniqueUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UniqueUserId",
                    Value = UniqueUserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetOrderDetailsResult>("EXEC @returnValue = [dbo].[GetOrderDetails] @UniqueUserId = @UniqueUserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
