// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace abbeys_bakery_api.Entities
{
    public partial class CartItem
    {
        public Guid CartItemId { get; set; }
        public Guid? MenuItemGuid { get; set; }
        public Guid? UniqueUserId { get; set; }
        public int? Quantity { get; set; }
    }
}