// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace abbeys_bakery_api.Entities
{
    public partial class GetOrderDetailsResult
    {
        [Column("Price", TypeName = "decimal(18,0)")]
        public decimal? Price { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public string AllergyNotes { get; set; }
    }
}
