// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using abbeys_bakery_api.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace abbeys_bakery_api.Entities
{
    public partial interface IAbbeysBakeryContextProcedures
    {
        Task<int> CreateOrderAsync(Guid? UniquUserId, Guid? UserTableId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetOrderDetailsResult>> GetOrderDetailsAsync(Guid? UniqueUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
