// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace abbeys_bakery_api.Entities;

public partial class MenuItem
{
    public decimal? Price { get; set; }

    public string ItemTitle { get; set; }

    public string ItemDescription { get; set; }

    public string AllergyNotes { get; set; }

    public Guid? MenuItemGuid { get; set; }
}